### ISSUE TITLE
Setting TTL on a movie results in the movie not being found in search

### ISSUE THREAD

**Issue by TobyHFerguson** [redis-developer/redis-microservices-demo#42]
I set TTL on the movie 'The Book of Life' (this is not connected to OMDB). Once it had expired from the Redis cache I could not find the movie in the search interface (it still showed up in the Movies (Legacy) interface. 

That's somewhat confusing, although I do understand what's happening. The movie has gone from the cache and been deleted from the search index ...

However, if I update the movie (I changed the plot) then, surprisingly, the movie is still not there. I think this is because only the changes to the movie are pushed into the stream and, given that this movie can't be found in Redis, the changes can't be linked to the underlying record. 

This means that any demonstration of the standard caching use case (i.e. with a TTL other than -1) is delicate - one has to have the right movie :-(

**Comment by tgrall** [comment]
* if you change or delete a movie in Redis it is true that nothing is pushed back to MySQL. (not implemented)
* but if you delete the value from the cache and update the MySQL record it should be recreated (all values are resent to the stream) and the message is processed here https://github.com/redis-developer/redis-microservices-demo/blob/c600b691bc88a9a99e75ea9fb52d06561ec202fd/streams-to-redisearch-service/src/main/java/io/redis/demos/services/search/service/StreamsToRediSearch.java#L580-L584. (not optimized since now update & create is more or less the same - it was different in RediSearch 1.x)

**Comment by tgrall** [comment]
@TobyHFerguson can you please test the new version and close the issue if you are ok with this
