### ISSUE TITLE
Question: Why do we have the local MySQL DB?

### ISSUE THREAD

**Issue by TobyHFerguson** [redis-developer/redis-microservices-demo#43]
I don't think I understand why we have the local MySQL DB, especially given the recent persistence enhancement.   I am struggling to explain what its doing in the architecture. I think its redundant. Maybe there's some facet of the demo I don't understand and which it was explaining but right now I don't get it :-( 

I can see that this is a half-way point, when you don't have persistence at the Redis layer, but once you've got persistence then I think there's a good argument to make that we can delete it. We could perhaps start the workshop without persistence, and then add it in as a step in the workshop, but this might be too much effort. The alternative would be to start with persistence enabled and simply drop the MySQL DB.

Comments?

**Comment by tgrall** [comment]
This is just the "story":

* you start from a legacy application (MySQL)
* you can easily 'modernize' this application using Redis (as a cache with hash, as a rich query engine, as a graph, ...) you adapt the story to the audience

The reason why I started with MySQL is because most applications are using RDBMS today, that are not necessary flexible, fast enough, or very hard to modified (not because of technical reason, but mostly because of internal process)

**Comment by TobyHFerguson** [comment]
AH - I thought the story started with the IMDB web service. I guess you just put the Web Service bit in to show caching, right?

**Comment by tgrall** [comment]
>  I guess you just put the Web Service bit in to show caching, right?

Yes

**Comment by TobyHFerguson** [comment]
OK - looks like I need to re-write. I clearly got the wrong end of the stick here. D'uh!
